# Generated by Django 4.2.6 on 2023-11-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='address',
        ),
        migrations.AddField(
            model_name='userregister',
            name='profile_pic',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
